---

nextcloud:
  user:
    name: nextcloud
  group:
    name: nextcloud
  service:
    name: nextcloud
    ports:
      http: 80
    restart:
      policy: always
  image:
    name: nextcloud
    tag: latest
  storage:
    base: "{{ storage_base }}/nextcloud_storage"
    directories: [
      config,
      custom_apps,
      data,
      themes
    ]
