---

emqx_deb:
emqx_edge_deb: https://www.emqx.io/downloads/edge/v3.2.2/emqx-edge-raspbian9-v3.2.2_armhf.deb
emqx_edge_zip: https://www.emqx.io/downloads/edge/v3.2.2/emqx-edge-docker-v3.2.2-arm32v7.zip

emqx_machine_image_tag_map:
  armv7l: '-arm32v7'
  x86_64: ''

emqx:
  image:
    name: emqx/emqx-edge
    tag: v3.2.2
  service:
    name: emqx
    ports:
      http: 8080
      mqtt: 1883
      mqtts: 11883
      ws: 8083
      ssl: 8883
      wss: 8084
    restart:
      policy: always
