---

- name: Add repository into source list
  become: yes
  apt_repository:
    repo: deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi
    state: present

#  sudo apt-get install -t stretch nginx php7.0 php7.0-curl php7.0-gd php7.0-fpm php7.0-cli php7.0-opcache php7.0-mbstring php7.0-xml php7.0-zip php7.0-mcrypt
- name: Install nginx
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
    - php7.0
    - php7.0-curl
    - php7.0-gd
    - php7.0-fpm
    - php7.0-cli
    - php7.0-opcache
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
    - php7.0-mcrypt

- name: Configure nginx
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  
- name: Copy config
  become: yes
  copy:
    dest: /etc/nginx/sites-enabled/kerberosio.conf
    src: kerberosio.conf

- name: Enable nginx service
  become: yes
  systemd:
    name: nginx
    enabled: yes

- name: Set name of autoremove script
  set_fact:
    kerberos_autoremove_scipt: 'autoremoval.sh'

- name: "Install kerberos autoremove script {{ kerberos_autoremove_scipt }}"
  copy:
    dest: "{{ ansible_user_dir }}/{{ kerberos_autoremove_scipt }}"
    src: "{{ kerberos_autoremove_scipt }}"
    mode: 0755

- name: Create cron job
  cron:
    name: "kerberos autoremove"
    minute: "*/15"
    job: "/bin/bash {{ ansible_user_dir }}/{{ kerberos_autoremove_scipt }}"
