---

- name: Copy job to /tmp
  template:
    src: emqx-edge.nomad.j2
    dest: /tmp/emqx-edge.nomad

- name: Run job
  command: nomad job run /tmp/emqx-edge.nomad
  register: nomad_emqx_job_submitted
