---

- set_fact:
    src_zip: https://www.emqx.io/downloads/edge/v3.1-beta.1/emqx-edge-docker-v3.1-beta.1.zip

- name: Download image
  get_url:
    src: https://www.emqx.io/downloads/edge/v3.1-beta.1/emqx-edge-docker-v3.1-beta.1.zip
    dest: /tmp/emqx-edge-docker.zip

- name: Unarchive iamge
  unarchive:
    src: /tmp/emqx-edge-docker.zip
    dest: /tmp/emqx-edge-docker

- name: Load image
  command: docker load < /tmp/emqx-edge-docker

