---

- name: Copy file
  become: yes
  copy:
    src: /tmp/emqx-edge.deb
    dest: /tmp/emqx-edge.deb

- name: Install package
  become: yes
  apt:
    deb: /tmp/emqx-edge.deb

- name: Start service
  become: yes
  systemd:
    name: emqx.service
    state: started
    enabled: yes

- name: "register {{ emqx.service.name }} service with the local consul agent"
  consul:
    service_name: "{{ emqx.service.name }}-{{ item.value }}"
    service_port: "{{ item.value }}"
    state: present
  with_dict: "{{ emqx.service.ports }}"
  when: service_consul_running
  