---

- hosts: hcnp-node-54

  vars:
    broker_package: emqx-edge

  tasks:

    - import_role:
        name: mosquitto
        tasks_from: nomad.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - mosquitto
        - services
      when: broker_package == 'mosquitto'

    - import_role:
        name: emq-x
        tasks_from: install.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - emqx
        - services
      when: broker_package == 'emqx-edge'
