---

- hosts: emqx_instances

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    - import_role:
        name: emqx
        tasks_from: container.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - emqx
