---

- hosts: emqx_instances

  pre_tasks:

    - name: Get emqx-edge
      get_url:
        url: "{{ emqx_edge_deb }}"
        dest: /tmp/emqx-edge.deb
      delegate_to: localhost

    # - name: Unarchive
    #   unarchive:
    #     src: /tmp/consul_exporter-0.5.0.linux-armv7.tar.gz
    #     dest: /tmp
    #   delegate_to: localhost
    
    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

    

  tasks:

    - name: Run emqx role
      become: true
      import_role:
        name: emqx-edge
        tasks_from: install.yml
      when: 1

    - import_role:
        name: emqx-edge
        tasks_from: nomad.yml
      environment:
        NOMAD_ADDR: "http://rpi-53:4646"
      tags:
        - emqx
      when: 0

