---

- hosts: nomad_server_instances

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    - import_role:
        name: emqx
        tasks_from: nomad.yml
      environment:
        NOMAD_ADDR: "http://rpi-53:4646"
      tags:
        - emqx
