---

- hosts: hcnp_nodes

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    - import_role:
        name: grafana
        tasks_from: docker.yml
      tags:
        - grafana
