---

- hosts: hcnp_nodes
 
  environment:
    TZ: "Australia/Adelaide"
    DOMAINNAME: "greenthegarden.io"

  vars:

    deploy_radicale: yes
    deploy_emqx: yes
    deploy_nextcloud: no
    deploy_openhab: yes
    deploy_homeassistant: no

    homeassistant_configuration_clone: no

  vars_prompt:

    - name: "github_user"
      prompt: "Enter github username"
      private: no
      when: homeassistant_configuration_clone

    - name: "github_password"
      prompt: "Enter github password"
      private: yes
      when: homeassistant_configuration_clone

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks


  tasks:

    - name: "Start EMQ-X"
      import_role:
        name: emqx
        tasks_from: container.yml
      tags:
        - mqtt
        - service
      when: deploy_emqx

    - name: "Configure Radicale"
      import_role:
        name: radicale
        tasks_from: configure.yml
      tags:
        - calendar
        - service
      when: deploy_radicale
      
    - name: "Start Radicale"
      import_role:
        name: radicale
        tasks_from: container.yml
      tags:
        - calendar
        - service
      when: deploy_radicale

    - name: "Start Nextcloud"
      import_role:
        name: nextcloud
        tasks_from: container.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - nextcloud
        - service
      when: deploy_nextcloud

    - name: "Configure openHAB"
      import_role:
        name: openhab
        tasks_from: configure.yml
      tags:
        - openhab
        - configuration
      when: deploy_openhab

    - name: "Start openHAB"
      import_role:
        name: openhab
        tasks_from: container.yml
      tags:
        - openhab
        - service
      when: deploy_openhab

    - name: "Configure home-assistant"
      import_role:
        name: home-assistant
        tasks_from: configure.yml
      tags:
        - homeassistant
        - configuration
      when: deploy_homeassistant

    - name: "Start home-assistant"
      import_role:
        name: home-assistant
        tasks_from: container.yml
      tags:
        - homeassistant
        - service
      when: deploy_homeassistant
