---

all:

  hosts:

    local-system:
      ansible_connection: local
      ansible_host: localhost
      consul_mode: server

  children:
  
    hcnp-nodes:
      hosts:
        local-system:

    consul_instances:
      hosts:
        local-system:
          consul_iface: eth0
          consul_node_role: bootstrap
          consul_bootstrap_expect: yes

    docker_instances:
      hosts:
        local-system:

    nomad_instances:
      hosts:
        local-system:
          nomad_node_role: both

    vault_instances:
      hosts:
        local-system:
