---

all:

  hosts:

    local-system:
      ansible_connection: local
      ansible_host: localhost
      consul_mode: server

  children:
  
    hcnp_nodes:
      hosts:
        local-system:

    emqx_instances:
      hosts:
        local-system:

    home_assistant_instances:
      hosts:
        local-system:
