---

all:

  hosts:

    local-system:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: philip
      consul_mode: server

  children:
  
    hcnp_nodes:
      hosts:
        local-system:

    emqx_instances:
      hosts:
        local-system:
