---

all:

  hosts:

    controller-node:
      ansible_host: localhost
      ansible_connection: local
    services-node-1:
      # ansible_hostname: services-node-1
      ansible_ssh_host: 172.16.1.101
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
      ansible_ssh_user: vagrant

  vars:

    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

  children:
  
    home_assistant_instances:
      hosts:
        services-node-1:
