---

all:

  hosts:

    # hcnp-node-50:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.1.50
    #   ansible_user: pi
    # hcnp-node-51:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.1.51
    #   ansible_user: pi
    # # hcnp-node-52:
    # #   ansible_connection: ssh
    # #   ansible_host: 192.168.1.52
    # #   ansible_user: pi
    # hcnp-node-53:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.1.53
    #   ansible_user: pi
    hcnp-node-54:
      ansible_connection: ssh
      # ansible_host: 192.168.1.54
      ansible_host: 192.168.1.8
      ansible_user: pi
    # hcnp-node-55:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.1.55
    #   ansible_user: pi
    # local-system:
    #   ansible_connection: local
    #   ansible_host: localhost
    #   ansible_user: philip
    #   consul_mode: server
    # camera-test:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.1.5
    #   ansible_user: pi
    # wb-node-48:
    #   ansible_connection: ssh
    #   ansible_host: 192.168.100.48
    #   ansible_user: ubuntu
    #   consul_mode: server

  children:
  
    hcnp_nodes:
      hosts:
        # hcnp-node-50:
        # hcnp-node-51:
        # hcnp-node-52:
        # hcnp-node-53:
        hcnp-node-54:
        # hcnp-node-55:

    emqx_instances:
      hosts:
        hcnp-node-54:
