---

all:

  hosts:

    localhost:
      ansible_connection: local
      ansible_host: localhost
      ansible_user: philip
      public_iface: wlp3s0
    hcnp-node-0:
      ansible_connection: ssh
      ansible_host: rpi-50
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-1:
      ansible_connection: ssh
      ansible_host: rpi-53
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-2:
      ansible_connection: ssh
      ansible_host: rpi-54
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0
    hcnp-node-3:
      ansible_connection: ssh
      ansible_host: rpi-55
      ansible_user: pi
      cluster_iface: eth0
      public_iface: eth0

  children:

    compute_nodes:
      hosts:
        hcnp-node-1:
        hcnp-node-2:
        hcnp-node-3:
      
    compute_servers:
      hosts:
        hcnp-node-1:
