---

- hosts: kerberos-nodes

  # remote_user: "{{ ansible_user }}"

  # vars:
  #    nextcloud_dir:       /var/www/html/nextcloud
  #    data_dir:            /var/nextcloud/data
     # database:            "{{ DATABASE | default('sqlite') }}"
     # mysql_root_password: "{{ MYSQL_ROOT_PASSWORD }}"
     # ncuser_password:     "{{ NCUSER_PASSWORD }}"

  roles:
    # - upgrade
    - pijuice
    - kerberos
