---

- hosts: camera_server_instances

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    - import_role:
        name: kerberos
        tasks_from: install-rpi-machinery.yml
      tags:
        - kerberos
        - installation
        
    - import_role:
        name: kerberos
        tasks_from: install-nginx-php.yml
      tags:
        - kerberos
        - installation
        
    - import_role:
        name: kerberos
        tasks_from: install-web-frontend.yml
      tags:
        - kerberos
        - installation
        