---

- hosts: hcnp_nodes

  vars:
    nextcloud_network: nextcloud_network

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    # - name: "Create nextcloud network"
    #   docker_network:
    #     name: "{{ nextcloud_network }}"

    # - import_role:
    #     name: nginx-proxy
    #     tasks_from: container-nextcloud
    #   tags:
    #     - nginx
    #     - services

    # - import_role:
    #     name: letsencrypt-nginx-proxy-companion
    #     tasks_from: container-nextcloud
    #   tags:
    #     - nginx
    #     - services

    # - import_role:
    #     name: mariadb
    #     tasks_from: container
    #   tags:
    #     - nginx
    #     - services

    - name: Install Docker
      import_role:
        name: geerlingguy.docker_arm

    - name: Start Redis
      import_role:
        name: geerlingguy.redis

    - name: Start Postresql
      import_role:
        name: geerlingguy.postgresql

    - import_role:
        name: nextcloud
        tasks_from: configure
      tags:
        - nextcloud
        - configuration

    - import_role:
        name: nextcloud
        tasks_from: container
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - nextcloud
        - services
