---

- hosts: hcnp_nodes

  vars:
    run_configuration: no

    service_consul_running: no
    service_docker_running: no

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  vars_prompt:

    - name: "github_user"
      prompt: "Enter github username"
      private: no

    - name: "github_password"
      prompt: "Enter github password"
      private: yes

  tasks:

    - name: Build an openHAB image with configuration
      docker_image:
        build:
          path: ./sinatra
        name: registry.ansible.com/chouseknecht/sinatra
        tag: v1
        push: yes
        source: build

    # - import_role:
    #     name: openhab
    #     tasks_from: configure.yml
    #   tags:
    #     - openhab
    #     - configuration
    #   when: run_configuration

    - import_role:
        name: openhab
        tasks_from: nomad.yml
      tags:
        - openhab
        - services
        