---

- hosts: compute_nodes

  vars:
    run_configuration: yes
    
  tasks:

    - import_role:
        name: openhab
        tasks_from: configure-users.yml
      tags:
        - openhab
        - configuration
      when: run_configuration


- hosts: hcnp-node-2

  vars:
    run_configuration: yes
    container_orchestration: ansible

    service_consul_running: no
    service_docker_running: no

    consul_server: '127.0.0.1:8500'

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  vars_prompt:

    - name: "github_user"
      prompt: "Enter github username"
      private: no
      when: run_configuration

    - name: "github_password"
      prompt: "Enter github password"
      private: yes
      when: run_configuration

  tasks:

    # - name: Build an openHAB image with configuration
    #   docker_image:
    #     build:
    #       path: ./sinatra
    #     name: registry.ansible.com/chouseknecht/sinatra
    #     tag: v1
    #     push: yes
    #     source: build

    - import_role:
        name: openhab
        tasks_from: configure-directories.yml
      tags:
        - openhab
        - configuration
      when: run_configuration

    - import_role:
        name: openhab
        tasks_from: nomad.yml
      tags:
        - openhab
        - services
      when: container_orchestration == "nomad"

    - import_role:
        name: openhab
        tasks_from: container.yml
      tags:
        - openhab
        - services
      when: container_orchestration == "ansible"
