---

- hosts: hcnp_nodes
 
  environment:
    TZ: "Australia/Adelaide"
    DOMAINNAME: "greenthegarden.io"

  vars:
    deploy_radicale: no
    deploy_emqx: yes
    deploy_openhab: yes
 
  vars_prompt:

    - name: "github_user"
      prompt: "Enter github username"
      private: no
      when: homeassistant_configuration_clone

    - name: "github_password"
      prompt: "Enter github password"
      private: yes
      when: homeassistant_configuration_clone

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks


  tasks:

    - name: "Start EMQ-X"
      import_role:
        name: emqx
        tasks_from: container.yml
      tags:
        - mqtt
        - service
      when: deploy_emqx

    - name: "Configure Radicale"
      import_role:
        name: radicale
        tasks_from: configure.yml
      tags:
        - calendar
        - service
      when: deploy_radicale
      
    - name: "Start Radicale"
      import_role:
        name: radicale
        tasks_from: container.yml
      tags:
        - calendar
        - service
      when: deploy_radicale

    - name: "Configure openHAB"
      import_role:
        name: openhab
        tasks_from: configure.yml
      tags:
        - openhab
        - configuration
      when: deploy_openhab

    - name: "Start openHAB"
      import_role:
        name: openhab
        tasks_from: container.yml
      tags:
        - openhab
        - service
      when: deploy_openhab
