---

- hosts: monitor_instances

  vars:
    service_consul_running: no

  pre_tasks:

    - name: "Run pre-tasks"
      import_role:
        name: pre-tasks

  tasks:

    - import_role:
        name: portainer
        tasks_from: container.yml
      tags:
        - portainer
        - services
