---

# Run up Cadvisor
- hosts: local-system

  tasks:

    - import_role:
        name: prometheus
        tasks_from: container.yml
      environment:
        NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
      tags:
        - prometheus
