---

# Create directories
- name: "Create base directory {{ openhab.directories.base }}"
  become: yes
  file:
    name: "{{ openhab.directories.base }}"
    state: directory
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755

# Create data directories
- name: Create data directories
  become: yes
  file:
    name: "{{ openhab.directories.base }}/{{ item }}"
    state: directory
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755
  loop: "{{ openhab.directories.data }}"

# Clone configuration
- name: "Clone configuration into {{ openhab.directories.base }}/conf"
  become: yes
  git:
    repo: 'https://{{ github_user | urlencode }}:{{ github_password | urlencode }}@{{ openhab.configuration.repo }}'
    # repo: 'https://github.com/greenthegarden/openhab2-configuration.git'
    dest: "{{ openhab.directories.base }}/conf"
    force: yes
    update: yes
  register: openhab_source
  
- name: "Set permissions on {{ openhab.directories.base }}/conf"
  become: yes
  file:
    dest: "{{ openhab.directories.base }}/conf"
    owner: "{{ openhab.user.name }}"
    group: "{{ openhab.group.name }}"
    mode: 0755
    recurse: yes
